### ISSUE TITLE
printf not found on vanilla Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by jettero** [run4flat/C-Blocks#2]
I did a fresh install of Alien::TinyCCx and C::Blocks and figured this would work first try:

```
use C::Blocks;
cblock {
    printf("hello world\n");
}
```

However, it's failing for me with this error:

```
C::Blocks compiler error:
./c-blocks-test.pl:7: error: undeclared function 'printf'
```

I've no clue what the problem is, but I'll try to figure it out later if I
don't hear anything else.

**Comment by run4flat** [comment]
Yeah, that documentation is old. What you're writing is kinda like this C code:

``` C
/* Notice no #include <stdio.h> */
int main() {
    printf("Hello world!\n");
}
```

Since you didn't include `stdio.h`, the compiler will complain that it doesn't know how to call the function. tcc itself issues the `undeclared function` message as a warning, and this example script used to run until I decided that undeclared functions are almost certainly bugs and should be elevated to full errors. At any rate, this works for me:

``` perl
use C::Blocks;
use C::Blocks::PerlAPI;
cblock {
    printf("hello world\n");
}
```

Out of curiosity, for hello-world sorts of scripts, do you suppose I should create the module `C::Blocks::stdio` so you get `printf` without having to pull in the Perl API?

**Comment by jettero** [comment]
Oh.  My ticket is invalid (mostly).  

Yeah, It makes sense to me to have C::Blocks::headers that are sortof on parity with the TinyCC headers (if they're different from the system libc includes).  Maybe ::stdio, ::strings, ::stdlib, etc.

Side note: my gcc is going to compile int main() { printf("hiya!!\n"); } ... it's just going to complain via warning.  It would only fail to build if I added -Werror.  Your intention is to never build on warning?

**Comment by run4flat** [comment]
No, I'd say it's a valid ticket about bad documentation, which I've just updated. I've also release v0.02, which can handle sigil variables with all three basic sigils, and works with much older Perls. :-)
